version: "3.9"

services:
  web:
    build: .
    command: daphne blog.asgi:application --bind 0.0.0.0 --port 8000
    volumes:
      - ./:/blog/
      - static_volume:/blog/static
      - media_volume:/blog/media
    ports:
      - 8000:8000
    env_file:
      - ./env

  db:
    image: postgres:14.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}

  nginx:
    image: nginx:1.21.6-alpine
    ports:
      - 80:80
      # - 443:443
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - static_volume:/blog/static
      - media_volume:/blog/media
      # TODO: Uncomment
      # - ./data/certbot/conf:/etc/letsencrypt
      # - ./data/certbot/www:/var/www/certbot

  # certbot:
    # image: certbot/certbot
    # volumes:
      # - ./data/certbot/conf:/etc/letsencrypt
      # - ./data/certbot/www:/var/www/certbot

volumes:
  postgres_data:
  static_volume:
  media_volume:
